spring:
  datasource:
    url: jdbc:mysql://rm-bp1z3kjls0l9871t4po.mysql.rds.aliyuncs.com:3306/stumanager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Xyl3331996
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml